# Generated by cucumber-sinatra. (2013-10-16 14:01:04 -0400)

require File.join(File.dirname(__FILE__), '..', '..', 'ws.rb')

require 'cucumber/rspec/doubles'
require 'rack/test'
require 'rspec'

module ServiceAccessControlWorld
  def authorization_token(login)
    require 'conjur/api'
    token = Conjur::API.new_from_key([$config[:namespace], login ].join('-'), api_key(login)).token
    "Token token=\"#{Base64.strict_encode64 token.to_json}\""
  end
  
  def api_key(login)
    env_key = "#{login.upcase}_API_KEY"
    $config[:api_keys][login.to_sym] or raise "No env_key"
  end
  
  def app
    Rack::Builder.new do
      run ServiceAccessControl
    end
  end
end

World(ServiceAccessControlWorld, Rack::Test::Methods, RSpec::Expectations, RSpec::Matchers)
